// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const Container: string;
export const NotFound: string;
export const glitch: string;
export const glitchTop: string;
export const glitchBotom: string;
