// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const Container: string;
export const ProfileImage: string;
export const Hero: string;
export const Title: string;
export const Subtitle: string;
export const Intro: string;
export const Image: string;
export const Social: string;
export const Calendly: string;
export const HeroContainer: string;
export const WavingHand: string;
export const wave: string;
