// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const Container: string;
export const ProfileImage: string;
export const Hero: string;
export const Title: string;
export const Subtitle: string;
export const Tag: string;
export const Intro: string;
export const ImagePrefix: string;
export const Image: string;
export const Social: string;
export const Calendly: string;
export const heroImageCont: string;
export const heroImage: string;
export const HeroContainer: string;
