import React from "react"

import { StaticImage } from "gatsby-plugin-image"

import * as classes from "./style.module.css"

export const AIBadge = () => (
  <div className={classes.badge}>
    <StaticImage src="../../images/ai.jpg" alt="Danijel Vincijanović" />
    <p>
      This article is proudly written by human.
      <br />
      <strong>No content was generated by AI.</strong>
    </p>
  </div>
)
