// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const References: string;
export const Reference: string;
export const ReferenceImage: string;
