// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const Header: string;
export const ContentWrapper: string;
export const TopNavigationBar: string;
export const NavLink: string;
export const NavLinkActive: string;
