import React from "react"

import { StaticImage } from "gatsby-plugin-image"

import * as classes from "./style.module.css"

type Props = {
  involvement: "none" | "partial" | "assisted" | "full"
}

const involvementMapping = {
  none: "No content was generated by AI.",
  partial: "AI was used for readability improvements.",
  assisted: "AI assisted in writing the article.",
  full: "AI wrote the article.",
}

export const AIBadge = ({ involvement = "none" }: Props) => (
  <div className={classes.badge}>
    <StaticImage
      className={classes.image}
      src="./ai.jpg"
      alt="Written by human"
    />
    <span>
      {involvement !== "full" && (
        <>
          This article is proudly written by Danijel Vincijanović.
          <br />
        </>
      )}
      <strong>{involvementMapping[involvement]}</strong>
    </span>
  </div>
)
