import React from "react"

import { StaticImage } from "gatsby-plugin-image"

import * as classes from "./style.module.css"

type Props = {
  involvement: "none" | "partial" | "assisted"
}

export const AIBadge = ({ involvement = "none" }: Props) => (
  <div className={classes.badge}>
    <StaticImage src="./ai.jpg" alt="Danijel Vincijanović" />
    {involvement === "none" && (
      <span>
        This article is proudly written by Danijel Vincijanović.
        <br />
        <strong>No content was generated by AI.</strong>
      </span>
    )}
    {involvement === "partial" && (
      <span>
        This article is proudly written by Danijel Vincijanović.
        <br />
        <strong>AI was used for readability improvements.</strong>
      </span>
    )}
    {involvement === "assisted" && (
      <span>
        This article is proudly written by Danijel Vincijanović.
        <br />
        <strong>AI assisted in writing the article.</strong>
      </span>
    )}
  </div>
)
