// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const Pre: string;
export const Line: string;
export const LineContent: string;
export const LineNumber: string;
