// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const Section: string;
export const Heading: string;
export const ContentWrapper: string;
